package com.srt.FreelanceMarketplace.domain.dto;

public enum NotificationTypeEnum {
    NEW_ORDER,
    NEW_PROPOSAL,
    NEW_REVIEW,
    NEW_ORDER_REPORT,
    ORDER_COMPLETED,
    MONEY_TRANSFERRED,
    ORDER_CANCELLED,
    ORDER_ACCEPTED,
    EXTEND_ORDER_DEADLINE_REQUEST,
    ORDER_EXTENSION_ACCEPTED,
    ORDER_EXTENSION_REJECTED,
}
